name: Deploy Theme to Simply.com

on:
  push:
    branches: [ master ]

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          
          local-dir: wp-content/themes/nordicbloom/
          server-dir: public_html/wp-content/themes/nordicbloom/
